### PR TITLE
evaluation session

### LINKED ISSUE #6: Session 2: Forecast evaluation
- An overview of forecasting models (10 mins)
- Practice session: Evaluating forecasts from a range of models (60 mins)

### PR DESCRIPTION
**Pull request by sbfnk**
closes #6

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
This looks good but I wonder if it's enough to just have the random walk model here? In the ensemble session we pull in the other models without introduction and I had thought we would do that here.

**Comment by seabbs** [comment]
I've queued for merging as I think it's good as is but point stands about multiple models and the course flow

**Comment by sbfnk** [comment]
> This looks good but I wonder if it's enough to just have the random walk model here? In the ensemble session we pull in the other models without introduction and I had thought we would do that here.

I've added a bit of introduction in #11 (where the different models are also compared), both in the lecture and session. I didn't think there was time to do more and explain all the models etc. given that we're not using stan or showing any model code.

**Comment by seabbs** [comment]
We could keep the r code simulation as extensions?

**Pull request merged**
